name: Terraform
on:
  push:
    branches: [ main ]
    paths:
    - 'layers/**'
    - 'modules/**'
    - '.vault-version'
    - '.github/workflows/terraform.yml'

permissions: write-all

jobs:
  terraform-layer-deploy:
    uses: jtcressy-home/actions-workflows/.github/workflows/terraform.yml@main
    with:
      path: /layers/deploy/
      environment: vault-deploy
      tailscale: false
      action: apply
      debug: ${{ github.event.inputs.debug || false }}
    secrets: inherit
  vault-deploy-check:
    runs-on: ubuntu-latest
    needs:
    - terraform-layer-deploy
    outputs:
      outcome: ${{ steps.check.outcome }}
    steps:
    - name: Check if Vault is healthy before proceeding with configuration
      id: check
      uses: gpuliyar/check-url-action@v1.0.1
      with:
        url: https://vault.jtcressy.net/v1/sys/health
        retry-count: 3
        retry-delay: 1000
        codes-allowed: 200
      continue-on-error: true
  terraform-layer-config:
    uses: jtcressy-home/actions-workflows/.github/workflows/terraform.yml@main
    if: needs.vault-deploy-check.outputs.outcome == 'success'
    needs:
    - terraform-layer-deploy
    - vault-deploy-check
    with:
      path: /layers/config/
      environment: vault-config
      tailscale: false
      action: apply
      debug: ${{ github.event.inputs.debug || false }}
    secrets: inherit