name: Terraform
on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '.github/workflows/terraform.yml'
  pull_request:
    paths:
    - '**'
    - '.github/workflows/terraform.yml'

permissions: write-all

jobs:
  terraform:
    uses: jtcressy-home/actions-workflows/.github/workflows/terraform.yml@main
    with:
      tailscale: false
      action: ${{ (github.event.ref == 'refs/heads/main' && 'apply -auto-approve') || 'plan' }}
      debug: ${{ github.event.inputs.debug || false }}
    secrets: inherit