name: Terraform
on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '.github/workflows/terraform.yml'
  workflow_dispatch:
  pull_request:
    paths:
    - '**'
    - '.github/workflows/terraform.yml'

permissions: write-all

jobs:
  terraform:
    uses: jtcressy-home/actions-workflows/terraform.yml@main
    with:
      tailscale: false
    secrets: inherit