name: Terraform Manual
on:
  workflow_dispatch:
    inputs:
      layer:
        description: 'Which layer to run against'
        required: true
        type: choice
        options:
          - "deploy"
          - "config"
      action:
        description: 'Terraform Action to Run'
        required: true
        type: choice
        options:
          - apply
          - plan
          - output
      arguments:
        description: 'Extra arguments for terraform action step'
        type: string
        default: ''
        required: false
      init-arguments:
        description: 'Extra arguments for terraform init step'
        type: string
        default: ''
        required: false
      debug:
        type: boolean
        default: false
        description: 'Enable extra debug jobs'
        required: false

permissions: write-all

jobs:
  terraform:
    uses: jtcressy-home/actions-workflows/.github/workflows/terraform.yml@main
    with:
      environment: vault-${{ github.event.inputs.layer }}
      path: /layers/${{ github.event.inputs.layer }}/
      action: ${{ github.event.inputs.action }}
      arguments: ${{ github.event.inputs.arguments }}
      init-arguments: ${{ github.event.inputs.arguments }}
      debug: ${{ github.event.inputs.debug == 'true' }}
    secrets: inherit