name: Vault Image Sync
on:
  push:
    paths:
    - '.vault-version'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Query .vault-version
      id: vault-version
      uses: juliangruber/read-file-action@v1
      with:
        path: .vault-version
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        project_id: ${{ vars.GCP_PROJECT_ID }}
        create_credentials_file: true
        export_environment_variables: true
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.0
      with:
        version: '>= 363.0.0'
    - name: Sync From Docker Hub to gcr.io
      run: |
        gcloud auth configure-docker -q
        export VAULT_VERSION=$(echo "${{ steps.vault-version.outputs.content }}" | tr -d '\n')
        docker pull docker.io/library/vault:$VAULT_VERSION
        docker tag docker.io/library/vault:$VAULT_VERSION us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/vault:$VAULT_VERSION
        docker push us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/vault:${{ steps.vault-version.outputs.content }}