name: Vault Image Sync
on:
  push:
    paths:
    - '.vault-version'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Query .vault-version
      id: vault-version
      uses: juliangruber/read-file-action@v1
      with:
        path: .vault-version
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v1.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Sync From Docker Hub to gcr.io
      run: |
        gcloud auth configure-docker -q
        export VAULT_VERSION=$(echo "${{ steps.vault-version.outputs.content }}" | tr -d '\n')
        docker pull docker.io/library/vault:$VAULT_VERSION
        docker tag docker.io/library/vault:$VAULT_VERSION us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/vault:$VAULT_VERSION
        docker push us.gcr.io/${{ secrets.GCP_PROJECT_ID }}/vault:${{ steps.vault-version.outputs.content }}